name: Build and Push to Dockerhub

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Download EarnApp installer
        run: wget -qO- https://brightdata.com/static/earnapp/install.sh > ./earnapp.sh

      - name: Get version
        run: grep VERSION= ./earnapp.sh | cut -d'"' -f2 > ./version

      - name: Build & Push - Latest Lite
        run: |
          docker buildx build --squash --push \
          -t madereddy/earnapp:$(cat ./version) \
          -t madereddy/earnapp:latest \
          --platform linux/amd64,linux/arm64 build/lite

      - name: Update Docker Hub Readme
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: madereddy/earnapp
          short-description: UNOFFICIAL image for BrightData's EarnApp.
          readme-filepath: DOCKERHUB_README.md
